name: Hello World

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Echo text
        run: echo "Hello, world!"
